-- New Albums imported
SELECT
	A.ALBUM_ID AS "Album ID",
	A.TITLE AS TITLE,
	AR.NAME AS "Artist Name",
	A.RELEASE_YEAR AS "Album Release Year",
	TO_CHAR(
		MIN(S.DATE_FIRST_LISTENED),
		'FMMonth FMDD, YYYY HH:MI:SS AM'
	) AS "Date Added"
FROM
	ALBUMS A
	JOIN ALBUM_ARTISTS AA ON A.ALBUM_ID = AA.ALBUM_ID
	JOIN ARTISTS AR ON AA.ARTIST_ID = AR.ARTIST_ID
	LEFT JOIN SONGS S ON S.ALBUM_ID = A.ALBUM_ID
GROUP BY
	A.ALBUM_ID,
	A.TITLE,
	AR.NAME,
	A.RELEASE_YEAR
ORDER BY
	A.ALBUM_ID DESC
LIMIT
	1;