-- New User With hashed password
SELECT
	USER_ID AS "User ID",
	USERNAME AS "Username",
	EMAIL AS "Email",
	PASSWORD_HASH AS "Password",
	TO_CHAR(CREATED_AT, 'FMMonth FMDD, YYYY HH:MI:SS AM') AS "Account Creation Date"
FROM
	USERS
ORDER BY
	CREATED_AT DESC;

-- New Albums imported
SELECT
	A.ALBUM_ID AS "Album ID",
	A.TITLE AS TITLE,
	AR.NAME AS "Artist Name",
	A.RELEASE_YEAR AS "Album Release Year",
	TO_CHAR(
		MIN(S.DATE_FIRST_LISTENED),
		'FMMonth FMDD, YYYY HH:MI:SS AM'
	) AS "Date Added"
FROM
	ALBUMS A
	JOIN ALBUM_ARTISTS AA ON A.ALBUM_ID = AA.ALBUM_ID
	JOIN ARTISTS AR ON AA.ARTIST_ID = AR.ARTIST_ID
	LEFT JOIN SONGS S ON S.ALBUM_ID = A.ALBUM_ID
GROUP BY
	A.ALBUM_ID,
	A.TITLE,
	AR.NAME,
	A.RELEASE_YEAR
ORDER BY
	A.ALBUM_ID DESC
LIMIT
	5;

-- Playback tracking
SELECT
	PH.PLAYBACK_ID AS "Playback ID",
	U.USERNAME AS USERNAME,
	S.TITLE AS "Song Title",
	STRING_AGG(AR.NAME, ', ') AS ARTISTS,
	TO_CHAR(PH.PLAYED_AT, 'FMMonth FMDD, YYYY HH:MI:SS AM') AS "Time Played At",
	PH.DURATION_PLAYED_SECONDS AS "Duration in Seconds",
	PH.COMPLETED
FROM
	PLAYBACK_HISTORY PH
	JOIN USERS U ON PH.USER_ID = U.USER_ID
	JOIN SONGS S ON PH.SONG_ID = S.SONG_ID
	LEFT JOIN SONG_ARTISTS SA ON S.SONG_ID = SA.SONG_ID
	LEFT JOIN ARTISTS AR ON SA.ARTIST_ID = AR.ARTIST_ID
WHERE
	PH.USER_ID = 8
GROUP BY
	PH.PLAYBACK_ID,
	U.USERNAME,
	S.TITLE,
	PH.PLAYED_AT,
	PH.DURATION_PLAYED_SECONDS,
	PH.COMPLETED
ORDER BY
	PH.PLAYED_AT DESC
LIMIT
	10;

-- Indexes
SELECT
	INDEXNAME,
	INDEXDEF
FROM
	PG_INDEXES
WHERE
	TABLENAME = 'playback_history';