SELECT
	S.SONG_ID,
	S.TITLE AS SONG_TITLE,
	A.ARTIST_ID,
	A.NAME AS ARTIST_NAME
FROM
	SONGS S
	JOIN SONG_ARTISTS SA ON S.SONG_ID = SA.SONG_ID
	JOIN ARTISTS A ON SA.ARTIST_ID = A.ARTIST_ID
WHERE
	S.SONG_ID BETWEEN 126 AND 137
ORDER BY
	S.SONG_ID,
	A.NAME;