-- ── Independent tables (no FKs) ──────────────────────────────────

CREATE TABLE users (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(255) NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       username VARCHAR(100) NOT NULL,
                       created_at TIMESTAMP(6) NOT NULL,
                       last_login TIMESTAMP(6),
                       PRIMARY KEY (user_id),
                       CONSTRAINT uq_users_email UNIQUE (email),
                       CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE artists (
                         artist_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         name VARCHAR(255) NOT NULL,
                         bio TEXT,
                         PRIMARY KEY (artist_id),
                         CONSTRAINT uq_artists_name UNIQUE (name)
);

CREATE TABLE genres (
                        genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        name VARCHAR(100) NOT NULL,
                        PRIMARY KEY (genre_id),
                        CONSTRAINT uq_genres_name UNIQUE (name)
);

CREATE TABLE albums (
                        album_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        title VARCHAR(255) NOT NULL,
                        release_year INTEGER,
                        album_art_path VARCHAR(500),
                        PRIMARY KEY (album_id)
);

-- ── Depends on albums ────────────────────────────────────────────

CREATE TABLE songs (
                       song_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       title VARCHAR(255) NOT NULL,
                       date_first_listened DATE,
                       listen_count INTEGER,
                       duration_seconds INTEGER,
                       file_path VARCHAR(500) NOT NULL,
                       file_format VARCHAR(10),
                       codec VARCHAR(50),
                       bit_rate INTEGER,
                       sample_rate INTEGER,
                       channels INTEGER,
                       file_size_bytes BIGINT,
                       track_number INTEGER,
                       content_fingerprint VARCHAR(64),
                       album_id BIGINT,
                       PRIMARY KEY (song_id),
                       CONSTRAINT uq_songs_file_path UNIQUE (file_path),
                       CONSTRAINT fk_songs_album FOREIGN KEY (album_id) REFERENCES albums(album_id)
);

CREATE INDEX idx_songs_content_fingerprint ON songs(content_fingerprint);

-- ── Join tables ───────────────────────────────────────────────────

CREATE TABLE song_artists (
                              song_id BIGINT NOT NULL,
                              artist_id BIGINT NOT NULL,
                              PRIMARY KEY (song_id, artist_id),
                              CONSTRAINT fk_song_artists_song FOREIGN KEY (song_id) REFERENCES songs(song_id),
                              CONSTRAINT fk_song_artists_artist FOREIGN KEY (artist_id) REFERENCES artists(artist_id)
);
CREATE INDEX idx_song_artists_song_id ON song_artists(song_id);
CREATE INDEX idx_song_artists_artist_id ON song_artists(artist_id);

CREATE TABLE song_genres (
                             song_id BIGINT NOT NULL,
                             genre_id BIGINT NOT NULL,
                             PRIMARY KEY (song_id, genre_id),
                             CONSTRAINT fk_song_genres_song FOREIGN KEY (song_id) REFERENCES songs(song_id),
                             CONSTRAINT fk_song_genres_genre FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
);
CREATE INDEX idx_song_genres_song_id ON song_genres(song_id);
CREATE INDEX idx_song_genres_genre_id ON song_genres(genre_id);

CREATE TABLE album_artists (
                               album_id BIGINT NOT NULL,
                               artist_id BIGINT NOT NULL,
                               PRIMARY KEY (album_id, artist_id),
                               CONSTRAINT fk_album_artists_album FOREIGN KEY (album_id) REFERENCES albums(album_id),
                               CONSTRAINT fk_album_artists_artist FOREIGN KEY (artist_id) REFERENCES artists(artist_id)
);
CREATE INDEX idx_album_artists_album_id ON album_artists(album_id);
CREATE INDEX idx_album_artists_artist_id ON album_artists(artist_id);

-- ── Depends on users ──────────────────────────────────────────────

CREATE TABLE playlists (
                           playlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           user_id BIGINT NOT NULL,
                           name VARCHAR(255) NOT NULL,
                           description TEXT,
                           created_at TIMESTAMP(6) NOT NULL,
                           is_public BOOLEAN,
                           PRIMARY KEY (playlist_id),
                           CONSTRAINT fk_playlists_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE playlist_songs (
                                playlist_id BIGINT NOT NULL,
                                song_id BIGINT NOT NULL,
                                PRIMARY KEY (playlist_id, song_id),
                                CONSTRAINT fk_playlist_songs_playlist FOREIGN KEY (playlist_id) REFERENCES playlists(playlist_id),
                                CONSTRAINT fk_playlist_songs_song FOREIGN KEY (song_id) REFERENCES songs(song_id)
);

CREATE TABLE favourites (
                            favourite_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            user_id BIGINT NOT NULL,
                            song_id BIGINT NOT NULL,
                            favourited_at TIMESTAMP(6) NOT NULL,
                            PRIMARY KEY (favourite_id),
                            CONSTRAINT uq_favourites_user_song UNIQUE (user_id, song_id),
                            CONSTRAINT fk_favourites_user FOREIGN KEY (user_id) REFERENCES users(user_id),
                            CONSTRAINT fk_favourites_song FOREIGN KEY (song_id) REFERENCES songs(song_id)
);

CREATE TABLE playback_history (
                                  playback_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                  user_id BIGINT NOT NULL,
                                  song_id BIGINT NOT NULL,
                                  played_at TIMESTAMP(6) NOT NULL,
                                  duration_played_seconds INTEGER,
                                  completed BOOLEAN,
                                  source VARCHAR(50),
                                  PRIMARY KEY (playback_id),
                                  CONSTRAINT fk_playback_user FOREIGN KEY (user_id) REFERENCES users(user_id),
                                  CONSTRAINT fk_playback_song FOREIGN KEY (song_id) REFERENCES songs(song_id)
);
CREATE INDEX idx_user_played_at ON playback_history(user_id, played_at);
CREATE INDEX idx_song_played_at ON playback_history(song_id, played_at);

CREATE TABLE sync_queue (
                            sync_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            user_id BIGINT NOT NULL,
                            action_type VARCHAR(50) NOT NULL,
                            data TEXT,
                            status VARCHAR(20),
                            created_at TIMESTAMP(6) NOT NULL,
                            synced_at TIMESTAMP(6),
                            PRIMARY KEY (sync_id),
                            CONSTRAINT fk_sync_queue_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- ── Report tables (depend on users, songs, artists, genres) ──────

CREATE TABLE monthly_reports (
                                 report_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                 generated_at TIMESTAMP(6) NOT NULL,
                                 report_month INTEGER NOT NULL,
                                 report_year INTEGER NOT NULL,
                                 total_listening_time_minutes INTEGER,
                                 total_songs_played INTEGER,
                                 top_album_id BIGINT,
                                 top_artist_id BIGINT,
                                 top_genre_id BIGINT,
                                 top_song_id BIGINT,
                                 user_id BIGINT NOT NULL,
                                 PRIMARY KEY (report_id),
                                 CONSTRAINT uq_monthly_report UNIQUE (user_id, report_year, report_month),
                                 CONSTRAINT fk_monthly_user FOREIGN KEY (user_id) REFERENCES users(user_id),
                                 CONSTRAINT fk_monthly_top_song FOREIGN KEY (top_song_id) REFERENCES songs(song_id),
                                 CONSTRAINT fk_monthly_top_artist FOREIGN KEY (top_artist_id) REFERENCES artists(artist_id),
                                 CONSTRAINT fk_monthly_top_album FOREIGN KEY (top_album_id) REFERENCES songs(song_id),
                                 CONSTRAINT fk_monthly_top_genre FOREIGN KEY (top_genre_id) REFERENCES genres(genre_id)
);

CREATE TABLE weekly_reports (
                                report_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                generated_at TIMESTAMP(6) NOT NULL,
                                week_of_year INTEGER NOT NULL,
                                report_year INTEGER NOT NULL,
                                total_listening_time_minutes INTEGER,
                                total_songs_played INTEGER,
                                top_album_id BIGINT,
                                top_artist_id BIGINT,
                                top_genre_id BIGINT,
                                top_song_id BIGINT,
                                user_id BIGINT NOT NULL,
                                PRIMARY KEY (report_id),
                                CONSTRAINT uq_weekly_report UNIQUE (user_id, report_year, week_of_year),
                                CONSTRAINT fk_weekly_user FOREIGN KEY (user_id) REFERENCES users(user_id),
                                CONSTRAINT fk_weekly_top_song FOREIGN KEY (top_song_id) REFERENCES songs(song_id),
                                CONSTRAINT fk_weekly_top_artist FOREIGN KEY (top_artist_id) REFERENCES artists(artist_id),
                                CONSTRAINT fk_weekly_top_album FOREIGN KEY (top_album_id) REFERENCES songs(song_id),
                                CONSTRAINT fk_weekly_top_genre FOREIGN KEY (top_genre_id) REFERENCES genres(genre_id)
);

CREATE TABLE year_end_reports (
                                  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                  generated_at TIMESTAMP(6) NOT NULL,
                                  report_year INTEGER NOT NULL,
                                  total_listening_time_minutes INTEGER,
                                  total_songs_played INTEGER,
                                  top_album_id BIGINT,
                                  top_artist_id BIGINT,
                                  top_genre_id BIGINT,
                                  top_song_id BIGINT,
                                  user_id BIGINT NOT NULL,
                                  PRIMARY KEY (report_id),
                                  CONSTRAINT uq_year_report UNIQUE (user_id, report_year),
                                  CONSTRAINT fk_year_user FOREIGN KEY (user_id) REFERENCES users(user_id),
                                  CONSTRAINT fk_year_top_song FOREIGN KEY (top_song_id) REFERENCES songs(song_id),
                                  CONSTRAINT fk_year_top_artist FOREIGN KEY (top_artist_id) REFERENCES artists(artist_id),
                                  CONSTRAINT fk_year_top_album FOREIGN KEY (top_album_id) REFERENCES songs(song_id),
                                  CONSTRAINT fk_year_top_genre FOREIGN KEY (top_genre_id) REFERENCES genres(genre_id)
);